services:
  nginx:
    build: .
    platform: linux/amd64
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    init: true
    ports:
      - "19321:19321"
    environment:
      - QEMU_GUEST_RANDOMIZE=0
      - QEMU_SET_ENV=ADDR_NO_RANDOMIZE=1
    tty: true
    stdin_open: true
