services:
  nginx:
    build: .
    platform: linux/amd64
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    init: true
    ports:
      - "19321:19321"
    tty: true
    stdin_open: true
